[project]
name = "coreweavehack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SlavaZinevich", email = "slavazinevich@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "wandb>=0.30.0",
    "weave>=0.53.9",
]

[project.scripts]
coreweavehack = "coreweavehack:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
