"""The scorers. Every scorer returns ``{"value": float}`` or ``{"value": None, "unevaluable": reason}``;
a missing value is never written as zero. The oracle's summary of a series is its mean over the rows
that were evaluable. Every series is a success rate in ``[0, 1]`` with ``1.0`` ideal — the convention
the watch-direction check reads.

Three series grade the *quality* of a solution rather than its correctness, because a pass that
already knows a convention differs from one that discovers it even when both pass:

- ``solution_economy`` — the knowing policy's calls over the calls the pass spent on budgeted tools,
  on a passed row; a failed row scores zero (it has no solution to be economical about); a task that
  declares no knowing floor is unevaluable;
- ``turn_economy`` — the same over model turns, the floor being one turn per knowing call and one
  to answer, so a pass that batches calls in one turn clips at ``1.0``;
- ``method_transfer`` — the pass's last shell command replayed in the task's metamorphic twin (the
  same names, columns and routes over different data): the command's last line of output names the
  twin's gold, or it does not. A method that transfers reads the convention; one that fits the
  instance — or a pass that read the file and computed in its head, leaving no replayable command —
  does not. Evaluable on a passed row of a task with a twin whose pass issued a shell command.
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any

import weave

import suite as _suite
from suite.tools import CAUSE_MARKERS


def _value(v: float | None, reason: str | None = None) -> dict[str, Any]:
    return {"value": v} if v is not None else {"value": None, "unevaluable": reason or "not evaluable"}


class TaskPassRate(weave.Scorer):
    name: str = "task_pass_rate"

    @weave.op
    def score(self, *, output: dict, task: str, **kwargs) -> dict:
        if output.get("error"):
            return _value(0.0)
        try:
            spec = _suite.current().by_id[task]
            return _value(1.0 if spec.check(output.get("result"), Path(output.get("workdir") or ".")) else 0.0)
        except Exception as e:  # a check that cannot run is not a failure of the task
            return _value(None, f"hidden test raised {type(e).__name__}")


class ErrorCausePresent(weave.Scorer):
    """A failed task's final error names its root cause. Passed tasks are not evaluable on this series."""

    name: str = "error_cause_present"

    @weave.op
    def score(self, *, output: dict, **kwargs) -> dict:
        err = output.get("error")
        if not err:
            return _value(None, "task did not fail; no error to grade")
        cause = (err.get("cause") or "") if isinstance(err, dict) else ""
        return _value(1.0 if any(k in cause for k in CAUSE_MARKERS) else 0.0)


class ToolBudgetRespected(weave.Scorer):
    """Every budgeted tool stayed within its budget. Tasks under no budget are not evaluable on this series."""

    name: str = "tool_budget_respected"

    @weave.op
    def score(self, *, output: dict, shell_budget: int | None, http_budget: int | None = None, **kwargs) -> dict:
        budgets = {"shell": shell_budget, "http": http_budget if http_budget is not None else _suite.current().faults.http_budget}
        budgets = {k: v for k, v in budgets.items() if v is not None}
        if not budgets:
            return _value(None, "task carries no budget")
        calls = {"shell": output.get("shell_calls", 0), "http": output.get("http_calls", 0)}
        return _value(1.0 if all(calls[k] <= v for k, v in budgets.items()) else 0.0)


class OutputSchemaValid(weave.Scorer):
    name: str = "output_schema_valid"

    @weave.op
    def score(self, *, output: dict, schema: dict, **kwargs) -> dict:
        if output.get("error"):
            return _value(None, "task failed; no output to validate")
        result = output.get("result")
        props = schema.get("properties", {}).get("result", {})
        return _value(1.0 if _matches(result, props) else 0.0)


def _matches(value: Any, spec: dict) -> bool:
    t = spec.get("type")
    if isinstance(t, list):  # a union of types: any of them satisfies the schema
        return any(_matches(value, {**spec, "type": one}) for one in t)
    if t == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if t == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if t == "string":
        return isinstance(value, str)
    if t == "object":
        return isinstance(value, dict) and all(k in value for k in spec.get("required", []))
    return value is not None


class SuiteHash(weave.Scorer):
    """The composition guard: 1.0 when the row was generated by the suite this run was pinned to."""

    name: str = "suite_hash"

    @weave.op
    def score(self, *, output: dict, **kwargs) -> dict:
        return _value(1.0 if output.get("suite_hash") == _suite.current().hash else 0.0)


def _passed(output: dict, task: str) -> bool | None:
    """The hidden check on this row, as ``TaskPassRate`` reads it; ``None`` when it cannot run."""
    if output.get("error"):
        return False
    try:
        return bool(_suite.current().by_id[task].check(output.get("result"), Path(output.get("workdir") or ".")))
    except Exception:
        return None


class SolutionEconomy(weave.Scorer):
    name: str = "solution_economy"

    @weave.op
    def score(self, *, output: dict, task: str, **kwargs) -> dict:
        spec = _suite.current().by_id.get(task)
        if spec is None or not spec.knowing:
            return _value(None, "task declares no knowing floor")
        passed = _passed(output, task)
        if passed is None:
            return _value(None, "hidden test could not run")
        if not passed:
            return _value(0.0)
        used = sum(output.get(f"{tool}_calls", 0) for tool in spec.knowing)
        floor = sum(spec.knowing.values())
        return _value(min(1.0, floor / used) if used else 1.0)


class TurnEconomy(weave.Scorer):
    name: str = "turn_economy"

    @weave.op
    def score(self, *, output: dict, task: str, **kwargs) -> dict:
        spec = _suite.current().by_id.get(task)
        if spec is None or not spec.knowing or output.get("turns") is None:
            return _value(None, "task declares no knowing floor, or the row records no turns")
        passed = _passed(output, task)
        if passed is None:
            return _value(None, "hidden test could not run")
        if not passed:
            return _value(0.0)
        floor = sum(spec.knowing.values()) + 1
        return _value(min(1.0, floor / max(1, int(output["turns"]))))


_NUMBERS = re.compile(r"-?\d+(?:\.\d+)?")


def replay(command: str, twin) -> tuple[bool, str]:
    """Run ``command`` in a fresh copy of the twin's world; whether a number on its last line of output is the twin's gold."""
    workdir = Path(tempfile.mkdtemp(prefix="hgi-twin-"))
    twin.setup(workdir)
    try:
        proc = subprocess.run(command, shell=True, cwd=workdir, capture_output=True, text=True, timeout=30)
    except subprocess.TimeoutExpired:
        return False, "timed out"
    lines = [line for line in proc.stdout.splitlines() if line.strip()]
    if proc.returncode != 0 or not lines:
        return False, f"exited {proc.returncode}: {proc.stderr.strip()[:120]}"
    last = lines[-1]
    candidates: list[Any] = []
    for token in _NUMBERS.findall(last):
        candidates.append(float(token) if "." in token else int(token))
    candidates.append(last.strip())
    return any(twin.check(c, workdir) for c in candidates), last[:120]


class MethodTransfer(weave.Scorer):
    name: str = "method_transfer"

    @weave.op
    def score(self, *, output: dict, task: str, **kwargs) -> dict:
        spec = _suite.current().by_id.get(task)
        if spec is None or spec.twin is None:
            return _value(None, "task has no metamorphic twin")
        passed = _passed(output, task)
        if passed is None:
            return _value(None, "hidden test could not run")
        if not passed:
            return _value(None, "task failed; no method to transfer")
        commands = output.get("commands") or []
        if not commands:
            return _value(None, "the pass issued no shell command")
        ok, _ = replay(commands[-1], spec.twin)
        return _value(1.0 if ok else 0.0)


SCORERS = [TaskPassRate, ErrorCausePresent, ToolBudgetRespected, OutputSchemaValid, SuiteHash, SolutionEconomy, TurnEconomy, MethodTransfer]
SERIES = [s.model_fields["name"].default for s in SCORERS]
