"""The scorers. Every scorer returns ``{"value": float}`` or ``{"value": None, "unevaluable": reason}``;
a missing value is never written as zero. The oracle's summary of a series is its mean over the rows
that were evaluable."""

from __future__ import annotations

from typing import Any

import weave

from suite.tasks import BY_ID, suite_hash


def _value(v: float | None, reason: str | None = None) -> dict[str, Any]:
    return {"value": v} if v is not None else {"value": None, "unevaluable": reason or "not evaluable"}


class TaskPassRate(weave.Scorer):
    name: str = "task_pass_rate"

    @weave.op
    def score(self, *, output: dict, task: str, **kwargs) -> dict:
        if output.get("error"):
            return _value(0.0)
        try:
            return _value(1.0 if BY_ID[task].check(output.get("result")) else 0.0)
        except Exception as e:  # a check that cannot run is not a failure of the task
            return _value(None, f"hidden test raised {type(e).__name__}")


class ErrorCausePresent(weave.Scorer):
    """A failed task's final error names its root cause. Passed tasks are not evaluable on this series."""

    name: str = "error_cause_present"

    @weave.op
    def score(self, *, output: dict, **kwargs) -> dict:
        err = output.get("error")
        if not err:
            return _value(None, "task did not fail; no error to grade")
        cause = (err.get("cause") or "") if isinstance(err, dict) else ""
        return _value(1.0 if any(k in cause for k in ("502", "budget", "404", "exited")) else 0.0)


class ToolBudgetRespected(weave.Scorer):
    name: str = "tool_budget_respected"

    @weave.op
    def score(self, *, output: dict, shell_budget: int | None, **kwargs) -> dict:
        if shell_budget is None:
            return _value(None, "task carries no budget")
        return _value(1.0 if output.get("shell_calls", 0) <= shell_budget else 0.0)


class OutputSchemaValid(weave.Scorer):
    name: str = "output_schema_valid"

    @weave.op
    def score(self, *, output: dict, schema: dict, **kwargs) -> dict:
        if output.get("error"):
            return _value(None, "task failed; no output to validate")
        result = output.get("result")
        props = schema.get("properties", {}).get("result", {})
        ok = _matches(result, props)
        return _value(1.0 if ok else 0.0)


def _matches(value: Any, spec: dict) -> bool:
    t = spec.get("type")
    if t == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if t == "string":
        return isinstance(value, str)
    if t == "object":
        return isinstance(value, dict) and all(k in value for k in spec.get("required", []))
    return value is not None


class SuiteHash(weave.Scorer):
    """The composition guard: 1.0 when the row was generated by the suite this run was pinned to."""

    name: str = "suite_hash"
    expected: str = suite_hash()

    @weave.op
    def score(self, *, output: dict, **kwargs) -> dict:
        return _value(1.0 if output.get("suite_hash") == self.expected else 0.0)


SCORERS = [TaskPassRate, ErrorCausePresent, ToolBudgetRespected, OutputSchemaValid, SuiteHash]
SERIES = [s.model_fields["name"].default for s in SCORERS]
