"""The scorers. Every scorer returns ``{"value": float}`` or ``{"value": None, "unevaluable": reason}``;
a missing value is never written as zero. The oracle's summary of a series is its mean over the rows
that were evaluable."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import weave

import suite as _suite
from suite.tools import CAUSE_MARKERS


def _value(v: float | None, reason: str | None = None) -> dict[str, Any]:
    return {"value": v} if v is not None else {"value": None, "unevaluable": reason or "not evaluable"}


class TaskPassRate(weave.Scorer):
    name: str = "task_pass_rate"

    @weave.op
    def score(self, *, output: dict, task: str, **kwargs) -> dict:
        if output.get("error"):
            return _value(0.0)
        try:
            spec = _suite.current().by_id[task]
            return _value(1.0 if spec.check(output.get("result"), Path(output.get("workdir") or ".")) else 0.0)
        except Exception as e:  # a check that cannot run is not a failure of the task
            return _value(None, f"hidden test raised {type(e).__name__}")


class ErrorCausePresent(weave.Scorer):
    """A failed task's final error names its root cause. Passed tasks are not evaluable on this series."""

    name: str = "error_cause_present"

    @weave.op
    def score(self, *, output: dict, **kwargs) -> dict:
        err = output.get("error")
        if not err:
            return _value(None, "task did not fail; no error to grade")
        cause = (err.get("cause") or "") if isinstance(err, dict) else ""
        return _value(1.0 if any(k in cause for k in CAUSE_MARKERS) else 0.0)


class ToolBudgetRespected(weave.Scorer):
    """Every budgeted tool stayed within its budget. Tasks under no budget are not evaluable on this series."""

    name: str = "tool_budget_respected"

    @weave.op
    def score(self, *, output: dict, shell_budget: int | None, http_budget: int | None = None, **kwargs) -> dict:
        budgets = {"shell": shell_budget, "http": http_budget if http_budget is not None else _suite.current().faults.http_budget}
        budgets = {k: v for k, v in budgets.items() if v is not None}
        if not budgets:
            return _value(None, "task carries no budget")
        calls = {"shell": output.get("shell_calls", 0), "http": output.get("http_calls", 0)}
        return _value(1.0 if all(calls[k] <= v for k, v in budgets.items()) else 0.0)


class OutputSchemaValid(weave.Scorer):
    name: str = "output_schema_valid"

    @weave.op
    def score(self, *, output: dict, schema: dict, **kwargs) -> dict:
        if output.get("error"):
            return _value(None, "task failed; no output to validate")
        result = output.get("result")
        props = schema.get("properties", {}).get("result", {})
        return _value(1.0 if _matches(result, props) else 0.0)


def _matches(value: Any, spec: dict) -> bool:
    t = spec.get("type")
    if t == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if t == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if t == "string":
        return isinstance(value, str)
    if t == "object":
        return isinstance(value, dict) and all(k in value for k in spec.get("required", []))
    return value is not None


class SuiteHash(weave.Scorer):
    """The composition guard: 1.0 when the row was generated by the suite this run was pinned to."""

    name: str = "suite_hash"

    @weave.op
    def score(self, *, output: dict, **kwargs) -> dict:
        return _value(1.0 if output.get("suite_hash") == _suite.current().hash else 0.0)


SCORERS = [TaskPassRate, ErrorCausePresent, ToolBudgetRespected, OutputSchemaValid, SuiteHash]
SERIES = [s.model_fields["name"].default for s in SCORERS]
