"""§ 9.2, slice 6a — the lens battery: decoy rejection scored in Weave.

The close lenses each carry a ``counterfactual`` — the overshoot they must
refuse: manufacturing a falsification to have one to report (L-0003), or
grading a pass that recovered as a defect (L-0004). The battery is a fixed
dataset of planted items, half of them **decoys** — a louder, non-causal
signal the counterfactual must reject — and half genuine **signals** the
lens should catch. A lens answered over the battery is scored on two axes,
both derived from the same run and written onto the lens's telemetry:

- ``decoy_rejection`` — the fraction of decoys the lens correctly rejected
  (filed nothing for); the floor gate of the close lenses;
- ``answer_variance`` — the spread of the lens's filings across the whole
  battery; a lens that files the same answer on every item (all or nothing)
  reads zero, the crystallization signal absent — the sub-second "checked"
  the count-and-provenance form guards against.

The battery is a ``weave.Evaluation`` over a ``weave.Dataset``, run the way
:mod:`hgi.evaluate` runs the world: each scorer is a fact series named
``lens-battery-v1/<scorer>`` and every lens answer is a traced ``pass``
call. Absent data reads ``unevaluable``, never zero.

Two seeded-positive controls reuse the same scorers, evaluation and
telemetry writer, each item walked in its own context:

- the **examiner control** (:func:`run_examiner_control`): for each
  examiner-hosted lens, a draft carrying a fault of that lens's class the
  angle must land on (the signal) and a plausible draft with no such fault it
  must not land on (the decoy), attacked through :func:`hgi.consolidate.attack`
  with a fixed evidence pack; the landing is ``signal_caught``, the
  non-landing ``decoy_rejection``, written onto the lens register;
- the **coder control** (:func:`run_coder_control`): an observation of a
  known work-shape the blind coder must return the term for, and one that
  fits no term it must escape from with ``other(<what>)``; the result is
  written to ``<store>/index/controls.json`` — a telemetry file beside the
  projections, written by this run and regenerated by nothing.
"""

from __future__ import annotations

import asyncio
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import weave
from pydantic import PrivateAttr

from hgi import coder as _coder
from hgi import drafting as _drafting
from hgi import model as _model
from hgi import registry as _registry
from hgi import roles
from hgi import tracing
from hgi.evaluate import Evaluation, _evaluate
from hgi.registry import is_escape
from hgi.store import Store, now
from hgi.types import Consolidation, Draft, Fact, LensTelemetry

LENS_BATTERY = "lens-battery-v1"
CONTROL = "K-0000"
"""The consolidation id the examiner control attacks under: a stand-in, the way the human queue's deferral uses one."""


# --- what counts as a filing -------------------------------------------------------------------

def is_filed(finding: Any) -> bool:
    """A finding files only when it cites something: a record id or an anchor. An answer with no id is not filed (§ 6.13)."""
    if not isinstance(finding, dict):
        return False
    if finding.get("record") or finding.get("id"):
        return True
    anchor = finding.get("anchor")
    if isinstance(anchor, dict):
        return any(anchor.get(k) for k in ("call", "path", "uri", "record"))
    return bool(anchor)


def filed_any(findings: Any) -> bool:
    return isinstance(findings, list) and any(is_filed(f) for f in findings)


# --- the planted dataset -----------------------------------------------------------------------

def _l0003_subject(*, consulted: list[dict], rows: list[dict], failed: list[str], scores: dict) -> dict[str, Any]:
    """The whole-pass subject L-0003 reads: what the pass may have made false in the store."""
    return {"consulted": consulted, "rows": rows, "failed": failed, "fires": [], "scores": scores}


def _l0004_subject(row: dict) -> dict[str, Any]:
    """The single-row subject L-0004 (and L-0009) reads: one artifact, its output and tool errors."""
    return {"task": row["task"], "prompt": f"the presentation for {row['task']}", "row": row, "consulted": []}


def _l0010_subject(*, off_map: bool, consulted: list[dict], failed: list[dict]) -> dict[str, Any]:
    """The whole-pass subject L-0010 reads: whether the pass fired off-map, and the failed rows a missing-rule noticing anchors on."""
    return {"off_map": off_map, "consulted": consulted, "failed": failed}


def battery_items(lens_id: str) -> list[dict[str, Any]]:
    """The fixed decoys and signals for a close lens. Two of each so the fractions and the variance are stable."""
    if lens_id == "L-0003":
        premise = [{"id": "D-battery", "decision": "carry the cause on every rethrow",
                    "premises": [{"id": "p1", "statement": "the scorer reads the final error", "status": "supported"}]}]
        return [
            {"kind": "decoy", "why": "scores fell but no store premise reversed — manufacturing a falsification to match the drop",
             "subject": _l0003_subject(consulted=premise, rows=[{"task": "t/a"}, {"task": "t/b"}],
                                       failed=["t/a", "t/b"], scores={"task_pass_rate": 0.20})},
            {"kind": "decoy", "why": "an unfamiliar task appeared — novelty, not a record made false",
             "subject": _l0003_subject(consulted=premise, rows=[{"task": "t/novel"}], failed=["t/novel"],
                                       scores={"task_pass_rate": 0.80})},
            {"kind": "signal", "why": "a consulted premise's falsifier was observed: the scorer now grades exit code only",
             "subject": _l0003_subject(
                 consulted=[{"id": "D-battery", "decision": "carry the cause on every rethrow",
                             "premises": [{"id": "p1", "statement": "the scorer reads the final error",
                                           "falsifier": "a scorer change that grades exit code only",
                                           "status": "reversed", "anchor": "weave:///battery/eval/scorer-change"}]}],
                 rows=[{"task": "t/exitcode"}], failed=[], scores={"error_cause_present": 0.0})},
            {"kind": "signal", "why": "a consulted record's hook now covers a shape it excludes: the payload is false where it fires",
             "subject": _l0003_subject(
                 consulted=[{"id": "D-battery2", "decision": "retry only transient tool faults",
                             "premises": [{"id": "p2", "statement": "the fault is transient",
                                           "falsifier": "a deterministic 400 retried as if transient",
                                           "status": "reversed", "anchor": "weave:///battery/eval/deterministic-400"}]}],
                 rows=[{"task": "t/400"}], failed=["t/400"], scores={"task_pass_rate": 0.50})},
        ]
    if lens_id == "L-0004":
        return [
            {"kind": "decoy", "why": "a transient fault fired mid-run but the task recovered and passed — loud, non-causal",
             "subject": _l0004_subject({"task": "decoy/recovered", "error": None,
                                        "tool_errors": [{"cause": "502 Bad Gateway", "transient": True}],
                                        "scores": {"task_pass_rate": {"value": 1.0}}, "call": "weave:///battery/call/d1"})},
            {"kind": "decoy", "why": "a long, alarming stdout on a task that passed — verbosity, not a defect",
             "subject": _l0004_subject({"task": "decoy/verbose", "error": None, "result": "WARNING " * 40,
                                        "tool_errors": [], "scores": {"task_pass_rate": {"value": 1.0}},
                                        "call": "weave:///battery/call/d2"})},
            {"kind": "signal", "why": "a task failed on a transient fault and the reported error named no cause",
             "subject": _l0004_subject({"task": "signal/uncaused", "error": {"message": "request failed", "cause": None},
                                        "tool_errors": [{"cause": "503 Service Unavailable", "transient": True}],
                                        "scores": {"task_pass_rate": {"value": 0.0}}, "call": "weave:///battery/call/s1"})},
            {"kind": "signal", "why": "a task named the transient cause and still failed: the call was not retried",
             "subject": _l0004_subject({"task": "signal/not-retried", "error": {"message": "timed out", "cause": "timeout"},
                                        "tool_errors": [{"cause": "timeout", "transient": True}],
                                        "scores": {"task_pass_rate": {"value": 0.0}}, "call": "weave:///battery/call/s2"})},
        ]
    if lens_id == "L-0009":
        return [
            {"kind": "decoy", "why": "a passed row whose only fault was a 502 that cleared on retry — transient, non-causal",
             "subject": _l0004_subject({"task": "decoy/retried-502", "error": None,
                                        "tool_errors": [{"cause": "502 Bad Gateway", "transient": True}],
                                        "scores": {"task_pass_rate": {"value": 1.0}}, "call": "weave:///battery/call/r1"})},
            {"kind": "decoy", "why": "a passed row whose only fault was a 503 that cleared on retry — transient, non-causal",
             "subject": _l0004_subject({"task": "decoy/retried-503", "error": None,
                                        "tool_errors": [{"cause": "503 Service Unavailable", "transient": True}],
                                        "scores": {"task_pass_rate": {"value": 1.0}}, "call": "weave:///battery/call/r2"})},
            {"kind": "signal", "why": "a passed row recovered from a route-guard convention: a 401 the first attempt missed, corrected with a token",
             "subject": _l0004_subject({"task": "signal/route-guarded", "error": None,
                                        "tool_errors": [{"cause": "HTTP 401 Unauthorized: routes under /secure require ?token=", "transient": False}],
                                        "scores": {"task_pass_rate": {"value": 1.0}}, "call": "weave:///battery/call/g1"})},
            {"kind": "signal", "why": "a passed row recovered from a route-version convention: a 410 the first attempt missed, corrected on the /v2 successor",
             "subject": _l0004_subject({"task": "signal/route-versioned", "error": None,
                                        "tool_errors": [{"cause": "HTTP 410 Gone: this API serves /v2/…", "transient": False}],
                                        "scores": {"task_pass_rate": {"value": 1.0}}, "call": "weave:///battery/call/g2"})},
        ]
    if lens_id == "L-0010":
        record = [{"id": "D-battery", "decision": "retry only transient tool faults", "premises": []}]
        return [
            {"kind": "decoy", "why": "a failed pass that DID consult a record — a hook fired, so this is not off-map",
             "subject": _l0010_subject(off_map=False, consulted=record,
                                       failed=[{"task": "t/consulted", "row": {"task": "t/consulted", "error": {"message": "failed with a record in context"}, "call": "weave:///battery/call/m1"}}])},
            {"kind": "decoy", "why": "a failed pass that consulted a record on another shape — a hook fired, still not off-map",
             "subject": _l0010_subject(off_map=False, consulted=record,
                                       failed=[{"task": "t/consulted2", "row": {"task": "t/consulted2", "error": {"message": "failed with a record in context"}, "call": "weave:///battery/call/m2"}}])},
            {"kind": "signal", "why": "a failed pass that consulted nothing — off-map, the store held no hook for this work",
             "subject": _l0010_subject(off_map=True, consulted=[],
                                       failed=[{"task": "t/offmap", "row": {"task": "t/offmap", "error": {"message": "unmatched failure"}, "call": "weave:///battery/call/o1"}}])},
            {"kind": "signal", "why": "a failed pass that consulted nothing on another shape — off-map, a missing rule",
             "subject": _l0010_subject(off_map=True, consulted=[],
                                       failed=[{"task": "t/offmap2", "row": {"task": "t/offmap2", "error": {"message": "unmatched failure"}, "call": "weave:///battery/call/o2"}}])},
        ]
    return []


def dataset_rows(lenses: list[Any]) -> list[dict[str, Any]]:
    """One row per planted item per lens; each row carries the lens spec it is answered against, so predict is self-contained."""
    rows = []
    for lens in lenses:
        spec = {"id": lens.id, "angle": lens.angle, "counterfactual": lens.counterfactual, "product": lens.product}
        for n, item in enumerate(battery_items(lens.id)):
            rows.append({"item": f"{lens.id}/{item['kind']}/{n}", "lens": lens.id, "lens_spec": spec,
                         "subject": item["subject"], "is_decoy": item["kind"] == "decoy", "kind": item["kind"]})
    return rows


# --- the examiner control's plants -------------------------------------------------------------

CONTROL_SKETCH: dict[str, Any] = {
    "decision": "Errors that wrap a failed tool call carry the underlying cause.",
    "counterfactual": "The overshoot is a wrapper that reports the cause but never recovers — observed in O-0001, where the task still failed.",
    "latch": "a tool call that fails; an error reported from a tool failure; a wrapper that rethrows",
    "terms": ["error-wrapping", "http-tool"], "not_this": ["a failure inside the model's own reasoning, with no tool call behind it"],
    "stakes": "a silent failure hides the cause the oracle scores on; passes score green while the fault persists",
    "context": "the same fork was observed in independent passes: O-0001, O-0002",
    "options": [{"name": "A — report the cause on every error", "judged": "chosen", "why": "the scorer reads the final error's cause"},
                {"name": "B — report only the message", "judged": "rejected", "why": "the cause is lost at the first rethrow"}],
    "premises": [{"id": "p1", "statement": "the oracle's error_cause_present scorer reads the final error's cause", "falsifier": "a scorer change that grades on exit code only"}],
    "watch": {"scorer": "error_cause_present", "comparator": "<", "value": 0.5, "persistence": 2},
    "residue": ["whether the cause named is the right one is judgment; the floor checks shape only"],
    "moot_when": "no tool in the layer can fail", "scopes": ["suite/tools"],
}
"""The plausible draft every examiner angle must not land on: the decoy, with no fault of any angle's class."""

CONTROL_EVIDENCE: dict[str, Any] = {"observation_sessions": ["S-0001", "S-0002"], "bar_independent": 2, "fault_rate": 0.0,
                                    "task_ids": ["sum_numbers", "count_lines"], "series": {}, "scores": {}, "evaluation": "suite-v1",
                                    "watch_scorer": "error_cause_present"}
"""The fixed evidence pack the control attacks under: two independent sessions, no transient fault in the window, two task ids."""

EXAMINER_FAULTS: dict[str, dict[str, Any]] = {
    "L-0006": {"why": "a premise the evidence refutes: it rests on transient faults and the window's fault rate is zero",
               "sketch": {"premises": [{"id": "p1", "statement": "a transient fault clears on the next call",
                                        "falsifier": "no transient fault in the trace store over the window"}]}},
    "L-0007": {"why": "the payload names the task it was seen in instead of the transferable shape",
               "sketch": {"decision": "The sum_numbers task's wrapper carries the HTTP cause on rethrow."}},
}
"""Per examiner lens, the fault of its class planted on the signal draft — as a sketch or evidence override of the decoy's.
The mechanical classes (independence, watch direction) are the code's and are proven by tests, not planted."""


def control_draft(store: Store, name: str, sketch: dict[str, Any]) -> Draft:
    """A planted draft: the sketch's judgment with the body derived the way every draft's is, never a hand-written mechanism."""
    body = _drafting.body(_drafting.sketch_of(sketch, store.registry), ["O-0001", "O-0002"], store.registry.bars, _model.model_id("pass"))
    return store.parse_as(Draft, {"uid": store.new_uid(), "name": name, "kind": "decision", "drafted_at": now().isoformat(), "proposed_by": LENS_BATTERY,
                                  "rung": "new-decision", "rung_why": "a planted control draft", "body": body, "evidence": ["O-0001", "O-0002"]})


def examiner_items(store: Store, lens_id: str) -> list[dict[str, Any]]:
    """The two plants for an examiner lens: the signal carrying a fault of its class, the decoy carrying none."""
    fault = EXAMINER_FAULTS.get(lens_id)
    if fault is None:
        return []
    decoy = control_draft(store, f"P-control-{lens_id}-decoy", CONTROL_SKETCH)
    signal = control_draft(store, f"P-control-{lens_id}-signal", {**CONTROL_SKETCH, **fault.get("sketch", {})})
    return [{"kind": "decoy", "why": "a plausible draft with no fault of this class", "draft": decoy, "evidence": CONTROL_EVIDENCE},
            {"kind": "signal", "why": fault["why"], "draft": signal, "evidence": {**CONTROL_EVIDENCE, **fault.get("evidence", {})}}]


def examiner_rows(store: Store, lenses: list[Any]) -> list[dict[str, Any]]:
    """One row per plant per examiner lens, the draft and evidence carried whole so predict is self-contained."""
    rows = []
    for lens in lenses:
        for n, item in enumerate(examiner_items(store, lens.id)):
            rows.append({"item": f"{lens.id}/{item['kind']}/{n}", "lens": lens.id, "draft": item["draft"].model_dump(by_alias=True, mode="json"),
                         "evidence": item["evidence"], "is_decoy": item["kind"] == "decoy", "kind": item["kind"]})
    return rows


# --- the coder control's plants ----------------------------------------------------------------

CODER = "coder"
"""The key the coder control's telemetry is grouped under — the role, since the coder walks no lens."""

CODER_ITEMS: list[dict[str, Any]] = [
    {"kind": "signal", "name": "control/paged-listing", "term": "listing-paged",
     "noticed": "task list_users returned only the first page of the listing and stopped; the route named the next page in a field the attempt ignored, so the count came up short"},
    {"kind": "decoy", "name": "control/misfit", "term": None,
     "noticed": "the answer given was 41 where the table summed to 42: the arithmetic slipped in the model's own reasoning, with nothing in the world behind it"},
]
"""An observation whose convention the coder must name the term for, and one with no world-convention behind it that it must escape from."""


def coder_rows() -> list[dict[str, Any]]:
    return [{"item": f"{CODER}/{item['kind']}/{n}", "lens": CODER, "name": item["name"], "noticed": item["noticed"], "term": item["term"],
             "is_decoy": item["kind"] == "decoy", "kind": item["kind"]} for n, item in enumerate(CODER_ITEMS)]


# --- the scorers -------------------------------------------------------------------------------

def _value(v: float | None, reason: str | None = None) -> dict[str, Any]:
    return {"value": v} if v is not None else {"value": None, "unevaluable": reason or "not evaluable"}


class DecoyRejection(weave.Scorer):
    """The floor gate: on a decoy, 1.0 when the lens filed nothing (rejected the plant), 0.0 when it took the bait. Signals are not evaluable here."""

    name: str = "decoy_rejection"

    @weave.op
    def score(self, *, output: dict, is_decoy: bool, **kwargs) -> dict:
        if not is_decoy:
            return _value(None, "not a decoy item")
        return _value(0.0 if output.get("filed") else 1.0)


class SignalCaught(weave.Scorer):
    """The complement: on a genuine signal, 1.0 when the lens filed it, 0.0 when it missed. Decoys are not evaluable here."""

    name: str = "signal_caught"

    @weave.op
    def score(self, *, output: dict, is_decoy: bool, **kwargs) -> dict:
        if is_decoy:
            return _value(None, "not a signal item")
        return _value(1.0 if output.get("filed") else 0.0)


SCORERS = [DecoyRejection, SignalCaught]


# --- the answerer ------------------------------------------------------------------------------

class LensBatteryModel(weave.Model):
    """Answers each battery item with the ``pass`` role, the way the close lenses are walked, and records whether it filed."""

    _outputs: list[dict[str, Any]] = PrivateAttr(default_factory=list)

    @property
    def outputs(self) -> list[dict[str, Any]]:
        return self._outputs

    @weave.op
    def predict(self, item: str, lens: str, lens_spec: dict, subject: dict, is_decoy: bool, kind: str) -> dict[str, Any]:
        payload = roles.request("lens", lens=lens_spec, subject=subject, empty_is_legal=roles.EMPTY_LENS_IS_LEGAL)
        c = _model.complete("pass", payload, records_in_context=[lens])
        out = c.json()
        if not isinstance(out, dict):
            out = {}
        findings = [f for f in out.get("findings", []) if isinstance(f, dict)]
        result = {"item": item, "lens": lens, "is_decoy": is_decoy, "kind": kind,
                  "answer": str(out.get("answer", "")), "findings": findings, "filed": filed_any(findings), "call": c.call}
        self._outputs.append(result)
        return result


class ExaminerControlModel(weave.Model):
    """Attacks each planted draft through the examiner fan, one angle in its own context, and records whether that angle landed."""

    _store: Any = PrivateAttr(default=None)
    _outputs: list[dict[str, Any]] = PrivateAttr(default_factory=list)

    def __init__(self, store: Store, **data: Any):
        super().__init__(**data)
        self._store = store

    @property
    def outputs(self) -> list[dict[str, Any]]:
        return self._outputs

    @weave.op
    def predict(self, item: str, lens: str, draft: dict, evidence: dict, is_decoy: bool, kind: str) -> dict[str, Any]:
        from hgi import consolidate as _consolidate

        store: Store = self._store
        angle = next(l for l in store.registry.lenses("examiner") if l.id == lens)
        record = Consolidation(id=CONTROL, started_at=now(), after_pass=0, sessions_read=[])
        payload, c = _consolidate.attack(store, record, store.parse_as(Draft, draft), evidence, lenses=[angle])
        claims = [x for x in payload["claims"] if x.get("lens") == lens]
        landed = any(x.get("landed") for x in claims)
        result = {"item": item, "lens": lens, "is_decoy": is_decoy, "kind": kind, "claims": claims, "filed": landed, "call": c.call if c else None}
        self._outputs.append(result)
        return result


class CoderControlModel(weave.Model):
    """Codes each planted observation blind and records whether the coder named the term, or escaped."""

    _store: Any = PrivateAttr(default=None)
    _outputs: list[dict[str, Any]] = PrivateAttr(default_factory=list)

    def __init__(self, store: Store, **data: Any):
        super().__init__(**data)
        self._store = store

    @property
    def outputs(self) -> list[dict[str, Any]]:
        return self._outputs

    @weave.op
    def predict(self, item: str, lens: str, name: str, noticed: str, term: str | None, is_decoy: bool, kind: str) -> dict[str, Any]:
        store: Store = self._store
        coded, call = _coder.code([{"name": name, "noticed": noticed}], store.registry.terms("convention"), session=LENS_BATTERY, records_in_context=[])
        terms = coded.get(name, [])
        registered = [t for t in terms if not is_escape(t)]
        escaped = [t for t in terms if is_escape(t)]
        # a signal is caught when the coder returned the planted term; a decoy is rejected when it escaped and named no term
        filed = (term in registered) if term else bool(registered) or not escaped
        result = {"item": item, "lens": lens, "is_decoy": is_decoy, "kind": kind, "terms": terms, "expected": term, "filed": filed, "call": call}
        self._outputs.append(result)
        return result


# --- telemetry and facts -----------------------------------------------------------------------

def _variance(xs: list[float]) -> float:
    if not xs:
        return 0.0
    mean = sum(xs) / len(xs)
    return sum((x - mean) ** 2 for x in xs) / len(xs)


def telemetry_from(outputs: list[dict[str, Any]]) -> dict[str, LensTelemetry]:
    """Per-lens telemetry, computed from the battery run: the decoy-rejection fraction, the signal-caught fraction and the filing variance.

    ``decoy_rejection`` and ``signal_caught`` are the two halves of the same run — the fraction of decoys the lens filed
    nothing for and the fraction of genuine signals it filed — so a lens that rejects every decoy but catches only half
    its signals reads a partial signal-miss on the register the decoy axis alone would hide.
    """
    by_lens: dict[str, list[dict]] = defaultdict(list)
    for o in outputs:
        by_lens[o["lens"]].append(o)
    telemetry = {}
    for lens_id, rows in by_lens.items():
        decoys = [r for r in rows if r["is_decoy"]]
        rejected = [r for r in decoys if not r["filed"]]
        signals = [r for r in rows if not r["is_decoy"]]
        caught = [r for r in signals if r["filed"]]
        variance = _variance([1.0 if r["filed"] else 0.0 for r in rows])
        if decoys:
            fraction = len(rejected) / len(decoys)
            decoy = f"{fraction:.2f} — {len(rejected)}/{len(decoys)} planted decoys rejected ({LENS_BATTERY})"
        else:
            decoy = f"unevaluable — no decoy in the battery ({LENS_BATTERY})"
        if signals:
            fraction = len(caught) / len(signals)
            signal = f"{fraction:.2f} — {len(caught)}/{len(signals)} planted signals caught ({LENS_BATTERY})"
        else:
            signal = f"unevaluable — no signal in the battery ({LENS_BATTERY})"
        spread = ("filings vary across" if variance > 0 else "the same filing on all") + f" {len(rows)} battery items"
        telemetry[lens_id] = LensTelemetry(answer_variance=f"{variance:.2f} — {spread} ({LENS_BATTERY})",
                                           decoy_rejection=decoy, signal_caught=signal)
    return telemetry


def facts_from(summary: dict[str, Any], as_of: datetime, source: str | None) -> dict[str, Fact]:
    """The battery's scorer means as fact series ``lens-battery-v1/<scorer>``; a series no row could evaluate reads unevaluable."""
    facts = {}
    for scorer in SCORERS:
        name = scorer.model_fields["name"].default
        block = summary.get(name) or summary.get(scorer.__name__) or {}
        mean = (block.get("value") or {}).get("mean") if isinstance(block, dict) else None
        series = f"{LENS_BATTERY}/{name}"
        facts[name] = Fact(series=series, value=mean, as_of=as_of, source=source) if mean is not None else \
            Fact(series=series, unevaluable="no row was evaluable on this series", as_of=as_of, source=source)
    return facts


@dataclass
class BatteryResult:
    telemetry: dict[str, LensTelemetry]
    facts: dict[str, Fact]
    run: str | None
    outputs: list[dict[str, Any]] = field(default_factory=list)


# --- the run -----------------------------------------------------------------------------------

def run_battery(store: Store, lenses: list[Any] | None = None) -> BatteryResult:
    """Run the battery over the store's close lenses and return the per-lens telemetry and the scorer facts."""
    tracing.init()
    lenses = lenses if lenses is not None else store.registry.lenses("close")
    rows = dataset_rows(lenses)
    if not rows:
        return BatteryResult(telemetry={}, facts={}, run=None, outputs=[])
    model = LensBatteryModel()
    dataset = weave.Dataset(name=f"{LENS_BATTERY}-{len(rows)}", rows=rows)
    evaluation = Evaluation(name=LENS_BATTERY, dataset=dataset, scorers=[s() for s in SCORERS],
                            evaluation_name=f"{tracing.run_label()}{LENS_BATTERY}")
    with tracing.attributes(role="lens-battery", records_in_context=[l.id for l in lenses]):
        summary, call = asyncio.run(_evaluate(evaluation, model))
    stamp = now()
    uri = tracing.call_uri(call)
    return BatteryResult(telemetry=telemetry_from(model.outputs), facts=facts_from(summary, stamp, uri),
                         run=uri, outputs=model.outputs)


def _run(store: Store, model: Any, rows: list[dict[str, Any]], label: str, records: list[str]) -> BatteryResult:
    """One traced evaluation over planted rows: the battery's scorers, the outputs' telemetry, the scorer facts."""
    if not rows:
        return BatteryResult(telemetry={}, facts={}, run=None, outputs=[])
    dataset = weave.Dataset(name=f"{LENS_BATTERY}-{label}-{len(rows)}", rows=rows)
    evaluation = Evaluation(name=LENS_BATTERY, dataset=dataset, scorers=[s() for s in SCORERS],
                            evaluation_name=f"{tracing.run_label()}{LENS_BATTERY} {label}")
    with tracing.attributes(role="lens-battery", records_in_context=records):
        summary, call = asyncio.run(_evaluate(evaluation, model))
    uri = tracing.call_uri(call)
    return BatteryResult(telemetry=telemetry_from(model.outputs), facts=facts_from(summary, now(), uri), run=uri, outputs=model.outputs)


def run_examiner_control(store: Store, lenses: list[Any] | None = None) -> BatteryResult:
    """The examiner control over the register's examiner-hosted lenses: per lens the telemetry of its landing on the planted
    fault and its non-landing on the plausible draft, each item walked in its own context."""
    tracing.init()
    lenses = lenses if lenses is not None else store.registry.lenses("examiner")
    return _run(store, ExaminerControlModel(store), examiner_rows(store, lenses), "examiner-control", [l.id for l in lenses])


def run_coder_control(store: Store) -> dict[str, Any]:
    """The coder control: the payload ``controls.json`` carries — the coder's telemetry strings, the facts, and every item's coding."""
    tracing.init()
    result = _run(store, CoderControlModel(store), coder_rows(), "coder-control", [])
    t = result.telemetry.get(CODER) or LensTelemetry()
    return {CODER: {"decoy_rejection": t.decoy_rejection, "signal_caught": _fact_cell(result.facts.get("signal_caught")),
                    "answer_variance": t.answer_variance, "run": result.run, "as_of": now().isoformat(),
                    "items": [{"item": o["item"], "kind": o["kind"], "expected": o["expected"], "terms": o["terms"], "filed": o["filed"], "call": o["call"]}
                              for o in result.outputs]}}


def _fact_cell(fact: Fact | None) -> str:
    if fact is None:
        return f"unevaluable — no row was evaluable ({LENS_BATTERY})"
    return f"{fact.value:.2f} ({LENS_BATTERY})" if fact.value is not None else f"unevaluable — {fact.unevaluable} ({LENS_BATTERY})"


def controls_path(store: Store):
    return store.index_dir / "controls.json"


def write_controls(store: Store, payload: dict[str, Any]) -> None:
    """Write the coder control's telemetry beside the projections; :mod:`hgi.index` regenerates every projection and leaves this file alone."""
    _registry.write_json(controls_path(store), payload)


def _miss_stream(steer_ids: list[str]) -> str:
    """The miss stream a lens reads: the steers whose indictment cites it — the misses of that lens a human caught."""
    if not steer_ids:
        return f"no steer cites this lens ({LENS_BATTERY})"
    n = len(steer_ids)
    return f"{n} steer{'' if n == 1 else 's'} cite{'s' if n == 1 else ''} this lens: {', '.join(sorted(steer_ids))}"


def populate_telemetry(store: Store, telemetry: dict[str, LensTelemetry]) -> list[str]:
    """Write the computed telemetry onto the lens register, moving each battered lens off ``design-stage``; returns the ids updated.

    The ``miss_stream`` cell is wired from real data here rather than in :func:`telemetry_from`, which sees only the
    battery outputs: a human steer's indictment can name a lens (:func:`hgi.steers.indictment`), and the stream a lens
    reads is the steers that cite it. The battery axes are the rest of the cell; the miss stream is the store's steers.
    """
    citing: dict[str, list[str]] = defaultdict(list)
    for steer in store.all("steer"):
        if steer.indicts is not None:  # type: ignore[attr-defined]
            citing[steer.indicts.record].append(steer.id)  # type: ignore[attr-defined]
    path = store.registry.path("lenses")
    raw = _registry.read_json(path)
    updated = []
    for item in raw:
        t = telemetry.get(item.get("id"))
        if t is not None:
            item["telemetry"] = {**t.model_dump(), "miss_stream": _miss_stream(citing.get(item["id"], []))}
            updated.append(item["id"])
    _registry.write_json(path, raw)
    return updated


# --- the command --------------------------------------------------------------------------------

def _report(label: str, result: BatteryResult) -> None:
    for lens_id, t in sorted(result.telemetry.items()):
        print(f"{lens_id}: decoy_rejection {t.decoy_rejection}; answer_variance {t.answer_variance}")
    scores = ", ".join(f"{k}={'unevaluable' if f.value is None else f'{f.value:.2f}'}" for k, f in result.facts.items())
    print(f"{LENS_BATTERY} {label}: {scores}" + (f"; run {result.run}" if result.run else "; untraced (no Weave project)"))


def _cmd(args, store_of, finish) -> int:
    store = store_of(args)
    battery = run_battery(store)
    updated = populate_telemetry(store, battery.telemetry)
    _report("close lenses", battery)
    examiner = run_examiner_control(store)
    updated += populate_telemetry(store, examiner.telemetry)
    _report("examiner control", examiner)
    coder = run_coder_control(store)
    write_controls(store, coder)
    print(f"{CODER}: signal_caught {coder[CODER]['signal_caught']}; decoy_rejection {coder[CODER]['decoy_rejection']} → {controls_path(store)}")
    finish(store, args, f"Lens battery: score decoy rejection and populate telemetry for {', '.join(updated) or 'no lens'}; the coder control to index/controls.json")
    return 0


def register(add, store_of, finish) -> None:
    p = add("lens-battery", "run the lens battery and the seeded controls: score decoy rejection, populate lens telemetry, write the coder control")
    p.set_defaults(fn=lambda args: _cmd(args, store_of, finish))
